//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCENTIVE_SCRF
    {
        public long ID { get; set; }
        public int EMPID { get; set; }
        public string IF_SCRF { get; set; }
        public int DATE_MONTH { get; set; }
        public int DATE_YEAR { get; set; }
        public string EMP_NAME { get; set; }
    }
}
