//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCENTIVE_DAYS_WORK
    {
        public int EMPID { get; set; }
        public string EMP_NAME { get; set; }
        public Nullable<decimal> NET { get; set; }
        public string OUTLET_NAME { get; set; }
        public string DTR_DATE { get; set; }
        public Nullable<int> OUTLET_NO { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
