//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_EMPLOYEE
    {
        public int EMPID { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string MI { get; set; }
        public string EMPLOYMENT_STATUS { get; set; }
        public string DIVISION { get; set; }
        public string DEPARTMENT { get; set; }
        public string PASSWORD { get; set; }
        public string SHORTNAME { get; set; }
        public string ACTIVE { get; set; }
        public string EXPIRED { get; set; }
        public string PASSKEY { get; set; }
        public int LOGIN_FAILED { get; set; }
        public string LOCKED { get; set; }
        public string ROLES { get; set; }
        public string USER_PROGRAM { get; set; }
        public int MODIFIED_BY { get; set; }
        public string MODIFIED_DATE { get; set; }
        public string SYSTEM_DATE { get; set; }
    }
}
