//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_OUTLET
    {
        public int OUTLET_NO { get; set; }
        public string OUTLET_NAME { get; set; }
        public string OUTLET_TYPE_DESC { get; set; }
        public string TRADE_NAME { get; set; }
        public string MALL_DESC { get; set; }
        public int AREA_CODE { get; set; }
        public string LOCATION { get; set; }
        public string BIR_TIN { get; set; }
        public string BIR_ACCDTN { get; set; }
        public string MACHINE_NO { get; set; }
        public string OUTLET_ADDRESS { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string BR_CODE { get; set; }
        public string N_CHECK { get; set; }
        public int CLAS_C { get; set; }
        public string CLAS_TRD_C { get; set; }
        public int STOR_NO { get; set; }
        public string TSL_SRL { get; set; }
        public int NAV_CODE { get; set; }
        public string MIN { get; set; }
        public string PERMIT_NO { get; set; }
        public int MODIFIED_BY { get; set; }
        public string MODIFIED_DATE { get; set; }
    }
}
