//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_SALES_INCENTIVE_AREA_BNK
    {
        public int EMPID { get; set; }
        public string BANK_ACCT_NO { get; set; }
    }
}
