//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_SALES_INCENTIVE_VIEW
    {
        public Nullable<int> OUTLET_NO { get; set; }
        public string OUTLET_NAME { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> YEAR { get; set; }
        public decimal TARGET_SALES { get; set; }
        public decimal NET_TARGET { get; set; }
        public decimal NETSALES { get; set; }
        public decimal DAYEND50 { get; set; }
        public decimal DAYEND20 { get; set; }
        public decimal VARIANCE { get; set; }
        public decimal SPOILAGE { get; set; }
        public Nullable<int> EMPID { get; set; }
        public string EMP_NAME { get; set; }
        public string COMPLAIN { get; set; }
        public int EMP_COUNT { get; set; }
        public int TOTAL_DAYS_WORK { get; set; }
    }
}
