//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_CREW_INCENTIVE
    {
        public long ID { get; set; }
        public string BRANCH { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string DAYS_WORK { get; set; }
        public string INCENTIVE_PER_DAY { get; set; }
        public string SPECIAL_PER_DATE { get; set; }
        public string TOTAL_INCENTIVE { get; set; }
        public string TOTAL_SPECIAL { get; set; }
        public string GRAND_TOTAL { get; set; }
    }
}
