//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_AREA_INCENTIVE
    {
        public long ID { get; set; }
        public string AREA_NAME { get; set; }
        public string INCENTIVE { get; set; }
        public string SPECIAL { get; set; }
        public string TOTAL { get; set; }
    }
}
