//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_SALES_INCENTIVE_QOUTLET
    {
        public string AREA_MANAGER { get; set; }
        public string OUTLET_NO { get; set; }
        public string OUTLET_NAME { get; set; }
        public string TARGET_NET { get; set; }
        public string TARGET_ACTUAL { get; set; }
        public string INCREMENTAL { get; set; }
        public string CLUSTER_INCENTIVE { get; set; }
        public string CREW_INCENTIVE { get; set; }
        public string CREW_SPECIAL { get; set; }
        public string CLUSTER_SPECIAL { get; set; }
        public string DAYEND_50 { get; set; }
        public string DAYEND_20 { get; set; }
        public string VARIANCE { get; set; }
        public string SPOILAGE { get; set; }
        public string COMPLAIN { get; set; }
        public long ID { get; set; }
        public string QUALIFIED { get; set; }
    }
}
