//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_SALES_INCENTIVE_QAREA
    {
        public string AREA_MANAGER { get; set; }
        public string TARGET_NET { get; set; }
        public string ACTUAL_NET { get; set; }
        public string INCREMENTAL { get; set; }
        public string DAYEND { get; set; }
        public string VARIANCE { get; set; }
        public string VARIANCE_PERCENT { get; set; }
        public string SPOILAGE { get; set; }
        public string SPOILAGE_PERCENT { get; set; }
        public long ID { get; set; }
        public string QUALIFIED { get; set; }
    }
}
