//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesIncentiveVariance
    {
        public long ID { get; set; }
        public Nullable<int> OutletNo { get; set; }
        public decimal Amount { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DateMonth { get; set; }
        public int DateYear { get; set; }
        public decimal Spoilage { get; set; }
    }
}
