//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SALES_INCENTIVE_NEW_BANK_FILE
    {
        public long ID { get; set; }
        public Nullable<int> EMPID { get; set; }
        public string EMP_NAME { get; set; }
        public string BANK_ACCOUNT { get; set; }
        public Nullable<decimal> INCENTIVE { get; set; }
        public Nullable<int> MONTH_DATE { get; set; }
        public Nullable<int> YEAR_DATE { get; set; }
        public string PARTICULARS { get; set; }
        public Nullable<int> GENERATED_BY { get; set; }
        public string GENERATED_DATE { get; set; }
        public string GROUP1 { get; set; }
        public string GROUP2 { get; set; }
        public string GROUP3 { get; set; }
        public string GROUP4 { get; set; }
        public string GROUP5 { get; set; }
        public string GROUP6 { get; set; }
        public string GROUP7 { get; set; }
        public string GROUP8 { get; set; }
        public string FINAL_PRODUCT { get; set; }
        public string PC_NAME { get; set; }
        public string COLUMN1 { get; set; }
        public string COLUMN2 { get; set; }
        public string COLUMN3 { get; set; }
        public string COLUMN4 { get; set; }
        public string COLUMN5 { get; set; }
    }
}
