//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesIncentive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SALES_INCENTIVE_NEW_SCRF
    {
        public Nullable<int> EMPID { get; set; }
        public string NAME { get; set; }
        public string BRANCH { get; set; }
        public string SCRF { get; set; }
        public string PERIOD_FROM { get; set; }
        public string PERIOD_TO { get; set; }
        public string MODIFIED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public string COLUMN1 { get; set; }
        public string COLUMN2 { get; set; }
        public string COLUMN3 { get; set; }
        public string COLUMN4 { get; set; }
        public string COLUMN5 { get; set; }
        public long ID { get; set; }
    }
}
